/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      // Material Design 3 风格色彩系统
      colors: {
        'on-surface': '#191c1d',
        'tertiary-fixed': '#ffdad7',
        'on-tertiary-container': '#711419',
        'background': '#f8f9fa',
        'outline-variant': '#bbcabf',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#005236',
        'on-primary-container': '#00422b',
        'surface-container': '#edeeef',
        'tertiary-fixed-dim': '#ffb3af',
        'surface-dim': '#d9dadb',
        'surface-variant': '#e1e3e4',
        'on-primary-fixed': '#002113',
        'secondary-fixed-dim': '#9ed2b5',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#3c4a42',
        'primary-fixed-dim': '#4edea3',
        'primary-container': '#10b981',
        'on-secondary-container': '#3c6c54',
        'inverse-surface': '#2e3132',
        'on-tertiary-fixed-variant': '#842225',
        'secondary-container': '#b7ebce',
        'on-tertiary-fixed': '#410005',
        'outline': '#6c7a71',
        'inverse-primary': '#4edea3',
        'error': '#ba1a1a',
        'secondary-fixed': '#baeed1',
        'secondary': '#376850',
        'primary-fixed': '#6ffbbe',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#002113',
        'tertiary': '#a43a3a',
        'surface-container-low': '#f3f4f5',
        'surface-tint': '#006c49',
        'on-background': '#191c1d',
        'inverse-on-surface': '#f0f1f2',
        'primary': '#006c49',
        'on-secondary-fixed-variant': '#1e4f3a',
        'tertiary-container': '#fc7c78',
        'surface-bright': '#f8f9fa',
        'surface-container-high': '#e7e8e9',
        'on-error-container': '#93000a',
        'surface': '#f8f9fa',
        'error-container': '#ffdad6',
        'surface-container-highest': '#e1e3e4',
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
